-- Card thumbnails for recipe photos.
--
-- The /recipes index (and later other card surfaces) shows a photo on each
-- card: the dish shot when one exists, else a detail crop of the first
-- source scan. Cards must serve proper web-sized derivatives, not multi-MB
-- originals — thumb_path points at a ~640px JPEG generated by sharp at
-- upload time (lib/storage/photos.ts) and stored under thumbs/ in the same
-- public recipe-photos bucket.
--
-- NULL means "no renderable thumbnail" (e.g. HEIC originals, which sharp's
-- prebuilt binaries can't decode) — the card falls back to its text-only
-- form, which is a dignified default, not an error state.

alter table photos
  add column if not exists thumb_path text;
